# Generated by Django 4.1.1 on 2023-02-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(max_length=30)),
                ('subcategory', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=50)),
                ('label_code', models.CharField(default='', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
