# Generated by Django 4.1.1 on 2022-09-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(max_length=30)),
                ('subcategory', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('CON', 'CONSUMABLE'), ('NON', 'NON-CONSUMABLE')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('label_code', models.CharField(default='', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
