# Generated by Django 4.1.1 on 2022-09-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
