# Generated by Django 4.1.1 on 2022-09-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_stock_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
