# Generated by Django 4.1.1 on 2022-09-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_stock_created_at_remove_stock_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateField(auto_created=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
