# Generated by Django 4.1.1 on 2022-09-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stock_created_at_alter_stock_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
