# Generated by Django 4.1.1 on 2022-09-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_stock_createdat_alter_stock_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updatedAt',
        ),
    ]
