# Generated by Django 4.1.1 on 2022-09-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_stock_user'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.stock'),
            preserve_default=False,
        ),
    ]
